language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install homeassistant
# command to run tests
script:
  - mv secrets.example.yaml secrets.yaml
  - hass --script check_config -c .