- platform: template
  switches:
    kitchen_light_automation:
      friendly_name: Kitchen light automation
      value_template: "{{ is_state('automation.kitchen_motion', 'on') }}"
      turn_on:
        service: automation.turn_on
        data:
          entity_id: 
            - automation.kitchen_motion
            - automation.kitchen_no_motion_10_mins
            - automation.kitchen_no_motion_25_mins
      turn_off:
        service: automation.turn_off
        data:
          entity_id: 
            - automation.kitchen_motion
            - automation.kitchen_no_motion_10_mins
            - automation.kitchen_no_motion_25_mins