title: Home
# Include external resources
#resources:
#  - url: /local/my-custom-card.js
#    type: js
#  - url: /local/my-webfont.css
#    type: css

# Optional background for all views. Check https://developer.mozilla.org/en-US/docs/Web/CSS/background for more examples.
#background: center / cover no-repeat url("/background.png") fixed
# Exclude entities from "Unused entities" view
#excluded_entities:
#  - weblink.router
views: 
    # View tab title.
  - icon: mdi:home
    title: Home
    id: home
    cards:
      - type: vertical-stack
        cards:
        - type: picture-glance
          title: "Hallway"
          entities: 
           - entity: group.hallway_lights
           - entity: climate.hallway
           - entity: binary_sensor.front_door
          image: https://lh3.googleusercontent.com/muER2maU0uCO89VaVOPjvtekb1cMwojNEjE1-BHpytJN10DYgaV4w1r9L4E6fPUt60mYmD_k36EbhDfmv-EQOoRVvfB-nwcyk1LCPX2C0MT4eM1shmIvV30ogWgVPOeo-WcC83j7CbsxmWcmV-03MOAi19j2a771MUYD-rGnYEMz8bvXZqYPG_2M8i-NTTF6SujTzHbprPZFcl2FGgLGkBznmBvgSv-Qb-Faqq024ov1MmEZQ4cZMHhoqbr1IpdNouvYBUyzc8PU2bxR4zXKkhfzVG_H1Er-hK9TV5cos7QSn_D1fEFNAlgv0f1E8WphUYknGwj6hASM6AxVtH7nF3A9QlUiFIHKhDl4Zlp93mPHzLd14zatZjqdjp_k7Q7G6R74w2xu3c93osJ0PpS2-RexMdjC_DNtIqMNQh2eCEgip0J6PkXIUFWm4datR0m4ywJ2lUmahM0kpvlEhD-7qBNo7xG-_99Rx0_smOpQAN-DEBRUUgEX1fokJaUHZtb3x2_LIws70jrWCK72pOhdVKRK3fnsfOce7ZAaAxiRGvmwqc19ouGID5iG1zFI8KEipU4rXNaCsOk2tdwvwGvztto02O6wZPsOxpRuTP1Wz8Qc5PbR8O49iEuAmJcltyw3xdc78nzyfwHhjfBqXK0zMDTUuivcE6GjUy9LtZ5tRULS_CZ-L5BCsKlP=w2718-h1528-no
          entity: group.hallway_lights
          tap_action: 
            action: navigate
            navigation_path: 2
          hold_acton:
            action: more-info
            
        - type: picture-glance
          title: "Living room"
          entities: 
           - entity: light.living_room
           #- entity: switch.christmas_tree
           - entity:  media_player.living_room
           - entity: media_player.living_room_tv
             icon: mdi:television
          image: https://lh3.googleusercontent.com/lnmrg4Iekt4tCqXs-8yQOxQ9KGDvuNX_lAM3bFM6Rvyaj8CrzAFfr-juCyPNexTudRqdfydHLzzTVRdlpSm7U9JOE709yjJlqRX0n9XordW5wjomfa5SoA4TxHfOrIkuA09EX0YffzmyrTshHuOUpyZ5_HfB9k1ngtRhkyw5BgqNq7mEN9rGb6fXiODV2MgTAEbCOUlNggS3PGmU2VF9w02XHEKH8nda6cenqTZjZtsA-oZPw5xbb8GipMBjm0QMYUGhvUwzXyA8SEbmv7Zjp2TozR2h5adlMUsFMm9du4SvXBTvZuxqIFzSJuaUGDItclq62n42FNpfsTuucVh32ba6AA3bkmvaekIlQmyYOdotSD-dd-R3KQHUu8WjXF2IcQoDhyrGcTb0oXknvtPgDRw-eRWKm7028p4idLtwJzZo_ekynHnyV5a9H93I5s-F3mqfRFzmSuf2rn7RIu1HvNmZ1ubu-9-sQUvymoYzEGE3hH8T6MaO8vG7gDqLjsx5tm4n3VVGGaCOS37aIgna3QerBx54V-DhIGSTdXGsB7byye_cQ_9wDch7XpCifwzm_IqdZvm7NQ10Q2Al0Ur4d7OK7nzH2JJWolN87868ZSs6KmruvmjDYAqbzdtsMXXpFhswdCgTHEDbfYvAS2TH2hkJrmhT6PG5vbRJIpGqxO-pdNGUE7OzagrO=w2718-h1528-no
          entity: light.living_room
          tap_action: 
            action: navigate
            navigation_path: 1
          hold_acton:
            action: more-info
        - type: picture-glance
          title: "Bedroom"
          entities: 
           - light.bedroom
           - media_player.bedroom
          image: https://lh3.googleusercontent.com/V0rU6lIQ71CBi6lWdrGYWEsB8vgp872Ig-sKEy64O1NlbK0PhtzbjfvCLYR66Z2o-EUss-P7w5VRh06FXXz33mFyJU0BqqXbJ51bmpZBOQ3MbEjffM8V-RiaAAs5w_p5mQoK7iceBDJYDqrumZu0eTQig4u48OYj77znb7edGrkneTI676PPaEeab-mNeymbbzMQQX4NFSFwF0Y4OTa2OxVp4v-C7V9v1XNUx-hz-Itba6H9oGI7cPxdLBLKaNw7iT6B0SPDTrYW5XgkzhTKt3L9Yn12GaMp-ATrH-vS_KH91KxxnJAKF5D507miLkmStmGhKltxhV76SeJJk14_yiKlVMmPmGKzzg4sasDLlJwDDhkP3GocQAVt4ZfKaIh7WwTzWWer75CDTXiqth6mkv7XNYOx2BsgRlFtw0thjot2aS0XsVpm9NVXl5wEr6Onw2zot-P2IisJMf484OiS2kdh5zuqBwX10xGF_WbWLux1q8bCzuNFSm14tdLq5LJy4Dd1C_l5E5c_la4Dn7kliz4AxkU11sTw2DqhuyGilpnDl1WvHQ-D320NDpU4jN-iOT-zE9McuUwvokVZAPJJEltU_69U0NMHESk6gddcohUYnrGS3aHqHsm1mYU3uJPsThEyiycofDK7iOmrS26Dyjpkvcv2cbT74RTbRGBJOlzSNDD3Y9SWRo9B=w2718-h1528-no
          entity: light.bedroom
          tap_action: 
            action: navigate
            navigation_path: 3
          hold_acton:
            action: more-info
        - type: picture-glance
          title: "Office"
          entities: 
           - switch.office_light
          image: https://lh3.googleusercontent.com/pw/ACtC-3cPHm3qSzPlY36pm_rm4EWDPUXbRVC8xxi6eZNcshzVSI-KZtiehXR5DKqylFjcHSB3pBp_dN_IZKCNG4wHefKYq0-PLppXUJuJa06QD00EbdlEf4tkQT7as_5ij8X4qAJOWAk4qDbGk6NU5HFT2PvsaQ=w1511-h850-no
          entity: switch.office_light
          tap_action: 
            action: navigate
            navigation_path: 4
          hold_acton:
            action: more-info
      - type: vertical-stack
        cards:
        - type: picture-glance
          title: "Kitchen"
          entities: 
           - group.kitchen_lights
           - media_player.kitchen
           - binary_sensor.motion_sensor_158d0001644d03
          image: https://lh3.googleusercontent.com/QNbRNymR-kLYIuWThqj3HLlS1wrKE9mUoGwsFxOBP9-SfmPuF0w70PEkXYms5kkHRH2SlstlzgIJN7S1L65G2BSxXIx8vDTep1D0-58Rk5nWaKe_GjdQuhi6oUUzQ4xrFgl2O093b7c7_QkwPlYBnriGmwivgxNMuKKwd8Th12WLFclG8353I68uAcwBOKXjxzKAeC2u4Zmwo9zHkPn3u2CdDbo-1SpvrR4o65t0sKInMINBb5pxkwcinOZfuf-baFWLmBvNK2IN8Ix3df-LipXWDsEzdCb3LOhrOS6b081lJq7rxJK-vdxxbX6NNKRnl82gj_khaxWqUoJ7WAphYCDVURukBxb8Gtxoijfs7GAS8pRWOdxYOb7qPyUJ5HHFCvwH6HFzsXSTiDQMgrZfDmisQWGk3DxTB8qGYrSGiXDZBGEsj8JK0KfUHe4pRK6mkboELDHHNYbLg8-u52Qi_7zhiifEV-aFOnKQ2yLWT06ANux1bdMYqEz7cbQbkKo-v3S03CJsbC3u8p2rNJS2it9Iqoij1lraWNiMuzNXIHp_e4vcZdpABapNZFoDoCgYV2LMhWVQgvqhiBKFd3Ova4ebhM3rHSePoU_RhwaVOdJgIWXasj1m7Qhjr-gHWN6JwxLmHR7iyAInnWSzq0QmsxUIErxb4mi6HRiFGfk_nhIRDDBgB9k-hzWw=w2718-h1528-no
          entity: group.kitchen_lights
          tap_action: 
            action: navigate
            navigation_path: 5
          hold_acton:
            action: more-info
        - type: picture-glance
          title: "Garden"
          entity: camera.garden
          camera_image: camera.garden
          camera_view: live
          entities:
            - switch.garden_lights
        - type: picture-glance
          title: "Front door"
          entity: camera.front_door
          camera_image: camera.front_door
          camera_view: live
          entities:
            - binary_sensor.front_door
        - type: picture-glance
          tap_action: 
            action: navigate
            navigation_path: 6
          image: https://lh3.googleusercontent.com/pw/ACtC-3fTtqcq1Cg7DMrIv6sKFukmatpBb6f3l0RbwnoY6D_hEXieXnu1LTj94z44FcyBa-mEQjpzS1Ct0yZesn43Ttx9VGbSrLFS4Qpca7Kqm3cGFO4XJZlyn_Uh8GDX4e6tGPTBqnJNORiAveb5JHy0jgFDbA=w640-h360-no?authuser=0
          entities:
            - sensor.evoque_alarm
            - device_tracker.evoque_device_tracker
            - sensor.evoque_info
            - sensor.evoque_last_trip
            - sensor.evoque_range
            - sensor.evoque_service_info
            - sensor.evoque_status
            - sensor.evoque_tyres
            - sensor.evoque_windows
        - type: conditional
          conditions:
            - entity: media_player.all_house
              state_not: "off"
          card:
            type: media-control
            entitiy: media_player.all_house
        - type: conditional
          conditions:
            - entity: media_player.downstairs
              state_not: "off"
          card:
            type: media-control
            entitiy: media_player.downstairs
      - type: vertical-stack
        cards:
        
        # The filter card will filter entities for their state
          - type: thermostat
            entity: climate.hallway
          - type: alarm-panel
            name: House Alarm
            entity: alarm_control_panel.house_alarm
          - type: glance
            entities:
              - person.carl
              - person.becs
              - person.ollie
              #- device_tracker.3c286dd0e0c2
              #- device_tracker.galaxys8lan
              #- device_tracker.androidfadcc20bfc24cd4blan
          - type: weather-forecast
            entity: weather.dark_sky
          - type: entities
            show_header_toggle: false
            entities:
              - script.bedtime
              - switch.smart_plug
              - sensor.next_bus_direction
              - sensor.next_bus_scheduled
              - sensor.next_bus_route
              - sensor.black_bin_date
              - sensor.brown_bin_date
              - sensor.blue_bin_date
    # View tab title.
  - icon: mdi:sofa
    title: Living room
    id: living_room
    # The cards to show on this view.
    cards:
      - type: picture-glance
        title: "Living room"
        entities: 
         - entity: light.living_room
         #- entity: switch.christmas_tree
         - entity:  media_player.soundbar
         - entity: media_player.sony_bravia_tv
           icon: mdi:television
        image: https://lh3.googleusercontent.com/lnmrg4Iekt4tCqXs-8yQOxQ9KGDvuNX_lAM3bFM6Rvyaj8CrzAFfr-juCyPNexTudRqdfydHLzzTVRdlpSm7U9JOE709yjJlqRX0n9XordW5wjomfa5SoA4TxHfOrIkuA09EX0YffzmyrTshHuOUpyZ5_HfB9k1ngtRhkyw5BgqNq7mEN9rGb6fXiODV2MgTAEbCOUlNggS3PGmU2VF9w02XHEKH8nda6cenqTZjZtsA-oZPw5xbb8GipMBjm0QMYUGhvUwzXyA8SEbmv7Zjp2TozR2h5adlMUsFMm9du4SvXBTvZuxqIFzSJuaUGDItclq62n42FNpfsTuucVh32ba6AA3bkmvaekIlQmyYOdotSD-dd-R3KQHUu8WjXF2IcQoDhyrGcTb0oXknvtPgDRw-eRWKm7028p4idLtwJzZo_ekynHnyV5a9H93I5s-F3mqfRFzmSuf2rn7RIu1HvNmZ1ubu-9-sQUvymoYzEGE3hH8T6MaO8vG7gDqLjsx5tm4n3VVGGaCOS37aIgna3QerBx54V-DhIGSTdXGsB7byye_cQ_9wDch7XpCifwzm_IqdZvm7NQ10Q2Al0Ur4d7OK7nzH2JJWolN87868ZSs6KmruvmjDYAqbzdtsMXXpFhswdCgTHEDbfYvAS2TH2hkJrmhT6PG5vbRJIpGqxO-pdNGUE7OzagrO=w2718-h1528-no
        entity: light.living_room
      - type: entities
        title: "Living room lights"
        show_header_toggle: true
        entities:
        - light.living_room_table_lamp
        - light.living_room_ceiling_1
        - light.living_room_ceiling_2
#      - type: conditional
#        conditions:
#          - entity: media_player.sony_bravia_tv
#            state_not: "off"
#        card:
#          type: media-control
#          entity: media_player.sony_bravia_tv
      - type: conditional
        conditions:
          - entity: media_player.living_room_tv
            state_not: "off"
        card:
          type: media-control
          entity: media_player.living_room_tv
      - type: conditional
        conditions:
          - entity: media_player.living_room
            state_not: "off"
        card:
          type: media-control
          entity: media_player.living_room
      - type: conditional
        conditions:
          - entity: media_player.ysp_1600_d5c2e7_main
            state_not: "off"
        card:
          type: media-control
          entity: media_player.ysp_1600_d5c2e7_main
    # View tab title.
  - icon: mdi:stairs
    title: Hallway
    id: hallway
    # The cards to show on this view.
    cards:
      - type: picture-glance
        title: "Hallway"
        entities: 
         - entity: group.hallway_lights
         - entity: climate.hallway
         - entity: binary_sensor.front_door
        image: https://lh3.googleusercontent.com/muER2maU0uCO89VaVOPjvtekb1cMwojNEjE1-BHpytJN10DYgaV4w1r9L4E6fPUt60mYmD_k36EbhDfmv-EQOoRVvfB-nwcyk1LCPX2C0MT4eM1shmIvV30ogWgVPOeo-WcC83j7CbsxmWcmV-03MOAi19j2a771MUYD-rGnYEMz8bvXZqYPG_2M8i-NTTF6SujTzHbprPZFcl2FGgLGkBznmBvgSv-Qb-Faqq024ov1MmEZQ4cZMHhoqbr1IpdNouvYBUyzc8PU2bxR4zXKkhfzVG_H1Er-hK9TV5cos7QSn_D1fEFNAlgv0f1E8WphUYknGwj6hASM6AxVtH7nF3A9QlUiFIHKhDl4Zlp93mPHzLd14zatZjqdjp_k7Q7G6R74w2xu3c93osJ0PpS2-RexMdjC_DNtIqMNQh2eCEgip0J6PkXIUFWm4datR0m4ywJ2lUmahM0kpvlEhD-7qBNo7xG-_99Rx0_smOpQAN-DEBRUUgEX1fokJaUHZtb3x2_LIws70jrWCK72pOhdVKRK3fnsfOce7ZAaAxiRGvmwqc19ouGID5iG1zFI8KEipU4rXNaCsOk2tdwvwGvztto02O6wZPsOxpRuTP1Wz8Qc5PbR8O49iEuAmJcltyw3xdc78nzyfwHhjfBqXK0zMDTUuivcE6GjUy9LtZ5tRULS_CZ-L5BCsKlP=w2718-h1528-no
        entity: group.hallway_lights
        
      - type: entities
        title: "Hallway lights"
        show_header_toggle: true
        entities:
        - light.porch
        - light.gateway_light_7811dcb38a39
        - light.attic_landing_light
        - binary_sensor.front_door
      - type: thermostat
        entity: climate.hallway
      - type: conditional
        conditions:
          - entity: media_player.living_room
            state_not: "off"
        card:
          type: media-control
          entity: media_player.living_room
    # View tab title.
  - icon: mdi:bed
    title: Bedroom
    id: bedroom
    # The cards to show on this view.
    cards:
      - type: picture-glance
        title: "Bedroom"
        entities: 
         - light.bedroom
         - media_player.bedroom
        image: https://lh3.googleusercontent.com/V0rU6lIQ71CBi6lWdrGYWEsB8vgp872Ig-sKEy64O1NlbK0PhtzbjfvCLYR66Z2o-EUss-P7w5VRh06FXXz33mFyJU0BqqXbJ51bmpZBOQ3MbEjffM8V-RiaAAs5w_p5mQoK7iceBDJYDqrumZu0eTQig4u48OYj77znb7edGrkneTI676PPaEeab-mNeymbbzMQQX4NFSFwF0Y4OTa2OxVp4v-C7V9v1XNUx-hz-Itba6H9oGI7cPxdLBLKaNw7iT6B0SPDTrYW5XgkzhTKt3L9Yn12GaMp-ATrH-vS_KH91KxxnJAKF5D507miLkmStmGhKltxhV76SeJJk14_yiKlVMmPmGKzzg4sasDLlJwDDhkP3GocQAVt4ZfKaIh7WwTzWWer75CDTXiqth6mkv7XNYOx2BsgRlFtw0thjot2aS0XsVpm9NVXl5wEr6Onw2zot-P2IisJMf484OiS2kdh5zuqBwX10xGF_WbWLux1q8bCzuNFSm14tdLq5LJy4Dd1C_l5E5c_la4Dn7kliz4AxkU11sTw2DqhuyGilpnDl1WvHQ-D320NDpU4jN-iOT-zE9McuUwvokVZAPJJEltU_69U0NMHESk6gddcohUYnrGS3aHqHsm1mYU3uJPsThEyiycofDK7iOmrS26Dyjpkvcv2cbT74RTbRGBJOlzSNDD3Y9SWRo9B=w2718-h1528-no
        entity: light.bedroom
        
      - type: entities
        title: "Bedroom lights"
        show_header_toggle: true
        entities:
        - light.bedside_left
        - light.bedside_right
      - type: conditional
        conditions:
          - entity: media_player.bedroom
            state: "on"
        card:
          type: media-control
          entity: media_player.bedroom
    # View tab title.
  - icon: mdi:desk
    title: Office
    id: office
    # The cards to show on this view.
    cards:
      - type: picture-glance
        title: "Office"
        entities: 
         - switch.office_light
        image: https://lh3.googleusercontent.com/pw/ACtC-3cPHm3qSzPlY36pm_rm4EWDPUXbRVC8xxi6eZNcshzVSI-KZtiehXR5DKqylFjcHSB3pBp_dN_IZKCNG4wHefKYq0-PLppXUJuJa06QD00EbdlEf4tkQT7as_5ij8X4qAJOWAk4qDbGk6NU5HFT2PvsaQ=w1511-h850-no
        entity: switch.office_light
      - type: entities
        title: "Office lights"
        show_header_toggle: true
        entities:
        - switch.office_light
    # View tab title.
  - icon: mdi:pot-mix
    title: Kitchen
    id: kitchen
    # The cards to show on this view.
    cards:
      - type: picture-glance
        title: "Kitchen"
        entities: 
         - group.kitchen_lights
         - media_player.kitchen
         - binary_sensor.motion_sensor_158d0001644d03
        image: https://lh3.googleusercontent.com/QNbRNymR-kLYIuWThqj3HLlS1wrKE9mUoGwsFxOBP9-SfmPuF0w70PEkXYms5kkHRH2SlstlzgIJN7S1L65G2BSxXIx8vDTep1D0-58Rk5nWaKe_GjdQuhi6oUUzQ4xrFgl2O093b7c7_QkwPlYBnriGmwivgxNMuKKwd8Th12WLFclG8353I68uAcwBOKXjxzKAeC2u4Zmwo9zHkPn3u2CdDbo-1SpvrR4o65t0sKInMINBb5pxkwcinOZfuf-baFWLmBvNK2IN8Ix3df-LipXWDsEzdCb3LOhrOS6b081lJq7rxJK-vdxxbX6NNKRnl82gj_khaxWqUoJ7WAphYCDVURukBxb8Gtxoijfs7GAS8pRWOdxYOb7qPyUJ5HHFCvwH6HFzsXSTiDQMgrZfDmisQWGk3DxTB8qGYrSGiXDZBGEsj8JK0KfUHe4pRK6mkboELDHHNYbLg8-u52Qi_7zhiifEV-aFOnKQ2yLWT06ANux1bdMYqEz7cbQbkKo-v3S03CJsbC3u8p2rNJS2it9Iqoij1lraWNiMuzNXIHp_e4vcZdpABapNZFoDoCgYV2LMhWVQgvqhiBKFd3Ova4ebhM3rHSePoU_RhwaVOdJgIWXasj1m7Qhjr-gHWN6JwxLmHR7iyAInnWSzq0QmsxUIErxb4mi6HRiFGfk_nhIRDDBgB9k-hzWw=w2718-h1528-no
        entity: group.kitchen_lights
      - type: entities
        title: "Kitchen lights"
        show_header_toggle: true
        entities:
        - light.mouse_lamp
        - light.kitchen_island_1
        - light.kitchen_island_2
      - type: conditional
        conditions:
          - entity: media_player.kitchen
            state_not: "off"
        card:
          type: media-control
          entity: media_player.kitchen
  - icon: mdi:car
    title: Car
    id: car
    # The cards to show on this view.
    cards:
      - type: entities
        entities:
          - sensor.evoque_alarm
          - device_tracker.evoque_device_tracker
          - lock.evoque_doors
          - sensor.evoque_info
          - sensor.evoque_last_trip
          - sensor.evoque_range
          - sensor.evoque_service_info
          - sensor.evoque_status
          - sensor.evoque_tyres
          - sensor.evoque_windows
      - type: conditional
        conditions:
          - entity: lock.evoque_doors
            state_not: "unlocked"
        card: 
          type: button
          entity: lock.evoque_doors
          hold_action:
            action: more-info
          icon: 'mdi:car-door'
          name: Unlock Doors
          show_icon: true
          show_name: true
          tap_action:
            action: call-service
            service: jlrincontrol.unlock_vehicle
            service_data:
              entity_id: sensor.evoque_info
              pin: "0302"
      - type: conditional
        conditions:
          - entity: lock.evoque_doors
            state_not: "locked"
        card: 
          type: button
          entity: lock.evoque_doors
          hold_action:
            action: more-info
          icon: 'mdi:car-door'
          name: Lock Doors
          show_icon: true
          show_name: true
          tap_action:
            action: call-service
            service: jlrincontrol.lock_vehicle
            service_data:
              entity_id: sensor.evoque_info
              pin: "0302"
      - type: button
        entity: sensor.evoque_info
        hold_action:
          action: more-info
        name: Pre heat car
        show_icon: true
        icon: 'mdi:fan'
        show_name: true
        tap_action:
          action: call-service
          service: jlrincontrol.start_preconditioning
          service_data:
            entity_id: sensor.evoque_info
            target_temp: 24
      - type: button
        entity: sensor.evoque_info
        hold_action:
          action: more-info
        icon: 'mdi:fan'
        name: Pre cool car
        show_icon: true
        show_name: true
        tap_action:
          action: call-service
          service: jlrincontrol.start_preconditioning
          service_data:
            entity_id: sensor.evoque_info
            target_temp: 15.5
      - type: button
        entity: sensor.evoque_info
        hold_action:
          action: more-info
        name: Update My Car
        show_icon: true
        show_name: true
        tap_action:
          action: call-service
          service: jlrincontrol.update_health_status
          service_data:
            entity_id: sensor.evoque_info